name: ci

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: Eslint
        run: yarn lint
        env:
          CI: true

  publish:
    needs: [test]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: Build package
        run: NODE_ENV=production yarn build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Feishu send msg to chat
        env:
          FEISHU_URL: https://open.feishu.cn/open-apis/bot/v2/hook/af6fb18f-106c-450d-8bda-0860d2c20970
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ env.FEISHU_URL }}
          method: "POST"
          customHeaders: '{"Content-Type":"application/json; charset=utf-8"}'
          data: '{"msg_type":"text","content":"{\"text\":\"ecs-api-sdk ${{ steps.get_version.outputs.VERSION }}版本 发布成功\"}"}'
